# Generated by Django 4.0.5 on 2022-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_products_category'),
        ('eshop_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='products',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products',
            field=models.ManyToManyField(to='shop_products.products'),
        ),
    ]
