# Generated by Django 4.0.5 on 2022-07-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_orders.orders'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products',
            field=models.ManyToManyField(to='shop_products.products'),
        ),
    ]
