# Generated by Django 4.0.5 on 2022-07-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزییات سبد خرید', 'verbose_name_plural': ' جزییات سبد های کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های کاربران'},
        ),
        migrations.CreateModel(
            name='FinishedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eshop_orders.orders', verbose_name='برای شخص')),
                ('products', models.ManyToManyField(to='eshop_orders.orderdetail', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'سبد خرید تمام شده',
                'verbose_name_plural': 'سبد های خرید به پایان رسیده',
            },
        ),
    ]
