# Generated by Django 4.0.5 on 2022-07-10 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('rate', models.CharField(choices=[(1, 'بد'), (2, 'نه چندات بد'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], max_length=100)),
                ('farsi_date_creation', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 7, 10, 21, 37, 17, 787355, tzinfo=utc), verbose_name='ایجاد شده')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.products', verbose_name='درباره')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
