# Generated by Django 4.0.5 on 2022-07-12 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_feedback', '0002_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='farsi_date_creation',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 7, 12, 12, 25, 38, 362105, tzinfo=utc), verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=100, verbose_name='رتبه'),
        ),
    ]
