# Generated by Django 4.0.5 on 2022-07-08 14:56

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='jdate_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='jdate_last_login',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 7, 8, 14, 56, 47, 935689, tzinfo=utc), verbose_name='تاریخ پیوستن!!!!!!'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین بازدید !!!'),
        ),
    ]
