# Generated by Django 4.0.5 on 2022-07-12 21:57

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0008_alter_account_date_joined_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 21, 57, 43, 330428, tzinfo=utc), null=True, verbose_name='تاریخ پیوستن!!!!!!'),
        ),
    ]
