# Generated by Django 4.0.5 on 2022-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='siteSettings/')),
                ('carousel_title', models.CharField(max_length=155)),
                ('carousel_title2', models.CharField(max_length=155)),
                ('carousel_text', models.TextField()),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
