# Generated by Django 4.0.5 on 2022-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'تنظیم سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='image',
            new_name='carousel_image',
        ),
        migrations.AddField(
            model_name='settings',
            name='carousel_text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='carousel_title',
            field=models.CharField(default='default', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='carousel_title2',
            field=models.CharField(default='default', max_length=155),
            preserve_default=False,
        ),
    ]
