# Generated by Django 4.0.5 on 2022-06-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0002_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='title',
        ),
    ]
