# Generated by Django 4.0.5 on 2022-06-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0003_remove_settings_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='copyright',
        ),
    ]
