# Generated by Django 4.0.5 on 2022-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products_category', '0001_initial'),
        ('shop_products', '0002_alter_products_options_alter_products_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop_products_category.productcategory', verbose_name='دسته بندی'),
        ),
    ]
