# Generated by Django 4.0.5 on 2022-07-16 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'get_latest_by': ['created_at'], 'ordering': ('title',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
