# Generated by Django 4.0.5 on 2022-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_alter_products_options_products_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'get_latest_by': ['created_at'], 'ordering': ('-created_at',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
