# Generated by Django 4.0.5 on 2022-07-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0004_alter_products_options_alter_products_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'get_latest_by': ['created_at_date'], 'ordering': ('-created_at_date',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='created_at',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='updated_at',
            new_name='updated_at_date',
        ),
    ]
