# Generated by Django 4.0.5 on 2022-07-16 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0005_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
