# Generated by Django 4.0.5 on 2022-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0006_alter_products_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_at_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
