# Generated by Django 4.0.5 on 2022-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'اطلاعات تماس با ما'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=155, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
    ]
