# Generated by Django 4.0.5 on 2022-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_products', '0002_alter_products_options_alter_products_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در url')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='برچسب زمان')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('products', models.ManyToManyField(blank=True, to='shop_products.products')),
            ],
        ),
    ]
