# Generated by Django 4.0.5 on 2022-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب / تگ', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='عنوان در url'),
        ),
    ]
